[package]
name = "test-module"
version = "0.3.0"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.34"
lazy_static = "1.0.0"
emacs = { path = ".." }
emacs-rs-module = { path = "../rs-module", version = "0.2.2" } # only for dev flow
