[package]
name = "test-module"
version = "0.5.2"
edition = "2018"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.34"
lazy_static = "1.3.0"
emacs = { path = "..", version = "0.5.2" }

[dev-dependencies]
emacs-rs-module = { path = "../rs-module", version = "0.5.0" }
