steps:
- powershell: |
    .\bin\test.ps1
  displayName: Run tests (Windows)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- bash: |
    ./bin/test
  displayName: Run tests
  condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'))
