[package]
name = "emacs_module_bindings"
version = "0.6.1"
authors = [
    "Aaron France <aaron.l.france@gmail.com",
    "Joey Ezechiëls <joey.ezechiels@gmail.com"
]
description = "Rust library for creating emacs modules"
license = "BSD-3-Clause"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.31"

[lib]
name = "emacs_module_bindings"
path = "src/lib.rs"
