[package]
name = "emacs"
version = "0.4.0"
description = "Rust library for creating emacs modules"
authors = [
    "Aaron France <aaron.l.france@gmail.com>",
    "Joey Ezechiëls <joey.ezechiels@gmail.com>",
    "Nguyễn Tuấn Anh <ubolonton@gmail.com>",
]
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["emacs", "emacs-module"]

[dependencies]
libc = "0.2.34"
lazy_static = "1.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
emacs_module = { path = "emacs-module", version = "0.3.0" }

[workspace]
members = [
    ".",
    "test-module",
    "rs-module",
]
