[package]
name = "emacs"
version = "0.2.0"
authors = [
    "Aaron France <aaron.l.france@gmail.com",
    "Joey Ezechiëls <joey.ezechiels@gmail.com",
    "Nguyễn Tuấn Anh <ubolonton@gmail.com>",
]
description = "Rust library for creating emacs modules"
license = "BSD-3-Clause"

[dependencies]
libc = "0.2.34"
lazy_static = "1.0.0"
emacs_module = { path = "emacs-module", version = "0.2.0" }

[workspace]
members = [
    ".",
    "test-module",
    "rs-module",
]
