[package]
name = "emacs_module_bindings"
version = "0.2.0"
authors = [
    "Aaron France <aaron.l.france@gmail.com",
    "Joey Ezechiëls <joey.ezechiels@gmail.com"
]
description = "Rust library for creating emacs modules"
license = "BSD-3-Clause"

[dependencies]
libc = "0.2"

[lib]

name = "emacs_module_bindings"
path = "src/lib.rs"
