[book]
title = "emacs-module-rs 0.13.0"
authors = ["ubolonton"]
multilingual = false
src = "src"

[output.html]
google-analytics = "UA-138609797-1"
additional-css = ["custom.css"]
preferred-dark-theme = "coal"